name: Sync Markdown Files

on:
  push:
    paths:
      - '**/*.md'
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Copy and format files to another repository
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const octokit = github.getOctokit(process.env.SYNC_FILES_TOKEN);

            const modifiedFiles = github.context.payload.commits.flatMap(commit => commit.modified);
            modifiedFiles.forEach(async (file) => {
              if (file.endsWith('.md')) {
                const filePath = path.join(process.env.GITHUB_WORKSPACE, file);
                const fileContent = fs.readFileSync(filePath, 'utf8');
                const lines = fileContent.split('\n');
                const firstLine = lines.find(line => line.trim() !== '');
                const title = path.basename(file, '.md');
                const pubDate = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric' });
                const tags = path.dirname(file).split('/').filter(Boolean);

                const frontMatter = `
                  ---
                  layout: ../../layouts/MarkdownPostLayout.astro
                  title: '${title}'
                  description: '${firstLine}'
                  pubDate: '${pubDate}'
                  tags: ['${tags.join("', '")}']
                  ---
                  `;
                const newContent = frontMatter + '\n' + fileContent;

                const targetFilePath = `src/pages/memos/${title}.md`;
                
                await octokit.rest.repos.createOrUpdateFileContents({
                  owner: 'roofeehim',
                  repo: 'roofeehim-blog',
                  path: targetFilePath,
                  message: `Sync Markdown file: ${title}`,
                  content: Buffer.from(newContent).toString('base64'),
                  branch: 'main',
                  committer: {
                    name: github.context.actor,
                    email: 'email@example.com'  // このメールアドレスを適宜変更してください
                  },
                  author: {
                    name: github.context.actor,
                    email: 'email@example.com'  // このメールアドレスを適宜変更してください
                  }
                });
              }
            });
