name: Sync Markdown Files

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  sync:
    runs-on: macos-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure we have the full git history

      - name: Install Dependencies
        run: brew install jq

      - name: Get list of changed markdown files
        id: changed_files
        run: |
          echo "Fetching changes between ${{ github.event.before }} and ${{ github.event.after }}"
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.md$' | xargs -n 1 basename || echo "")
          echo "Changed files: $CHANGED_FILES"
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No markdown files changed."
            exit 0  # Exit successfully if no changes
          else
            echo "::set-output name=markdown_files::$CHANGED_FILES"
          fi 

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: 'roofeehim/roofeehim-blog'
          token: ${{ secrets.SYNC_FILES_TOKEN }}
          path: 'target-repo'

      - name: Copy changed files to target repository
        run: |
          for file in ${{ steps.changed_files.outputs.markdown_files }}; do
            echo "Processing file: $file"
            cp "$file" "target-repo/src/pages/memos/$file"
            if [ $? -ne 0 ]; then
              echo "Failed to copy $file"
              exit 1
            fi
          done

      - name: Commit and push changes
        run: |
          cd target-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Sync Markdown files from source"
            git push
          fi